# ============================================
# AnKhangCRM RuboCop Configuration
# ============================================

plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# ==========================================
# Layout
# ==========================================
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'

Layout/EndOfLine:
  Enabled: false  # Allow CRLF on Windows

# ==========================================
# Metrics
# ==========================================
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'db/queue_schema.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

# ==========================================
# Style
# ==========================================
Style/Documentation:
  Enabled: false  # Skip class documentation

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'Gemfile'
    - 'Rakefile'

Style/StringLiterals:
  EnforcedStyle: double_quotes  # Allow "strings" (Rails default)

Style/SymbolArray:
  Exclude:
    - 'config/**/*'

# ==========================================
# Rails
# ==========================================
Rails:
  Enabled: true

Rails/Exit:
  Exclude:
    - "spec/**/*"  # RSpec generator uses abort

# ==========================================
# Rails-specific exclusions
# ==========================================

# I18n: Allow hardcoded Vietnamese for MVP, will migrate to locales later
Rails/I18nLocaleTexts:
  Enabled: false  # TODO: Enable and migrate to config/locales in Phase 2

# Devise controllers use callbacks for inherited actions
Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/controllers/users/passwords_controller.rb'

# ==========================================
# Naming
# ==========================================

# has_role? is clearer than role? for authorization checks
Naming/PredicatePrefix:
  Exclude:
    - 'app/models/user.rb'
    - 'app/helpers/authorization_helper.rb'

# ==========================================
# Metrics relaxations for helpers
# ==========================================

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/helpers/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/**/*'

# ==========================================
# Lint
# ==========================================

# Allow private constants when organizing code
Lint/UselessConstantScoping:
  Enabled: false
